/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ipclient;

import java.io.File;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Unpublish extends javax.swing.JFrame {
    DashBoard parent;
    IPClient root;
    /**
     * Creates new form Unpublish
     */
    public Unpublish(DashBoard d, IPClient rt) {
        initComponents();
        parent = d;
        root = rt;
        Vector files = new Vector();
        File dir = new File("C:/GangsharedFiles/");
        String fileNames[] = dir.list();
        if(fileNames != null){
            for(int i=0; i<fileNames.length; i++){
                files.add(fileNames[i]);
            }
            jButtonUnpublish.setEnabled(true);
        }
        else{
            files.add("No files Shared");
            jButtonUnpublish.setEnabled(false);
        }
        jListFiles.setListData(files);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListFiles = new javax.swing.JList();
        jButtonUnpublish = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListFiles);

        jButtonUnpublish.setText("Unpublish");
        jButtonUnpublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnpublishActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButtonUnpublish)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUnpublish)
                    .addComponent(jButtonBack))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUnpublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnpublishActionPerformed
        try {
            // TODO add your handling code here:
            if(jListFiles.getSelectedIndex() == -1) return;
            String fileName = jListFiles.getSelectedValue()+"";
            String msg = "25:"+fileName;
            root.sendMsg(msg);
            
            char[] ch = new char[1000];	
            int i = 0, c=0;;
            while (( c = root.in.read()) != '\n') {
                ch[i] = (char) c;
                i++;
            //System.out.print((char) c);
            }
            String response = new String(ch);
            response = response.trim();
            System.out.println("Response from server : " + response);
            StringTokenizer st = new StringTokenizer(response, ":");
            if(st.nextToken().equals("26")){
                int result = Integer.parseInt(st.nextToken());
                if(result == 1 && new File("C:/GangsharedFiles/" + fileName).delete()){
                    JOptionPane.showMessageDialog(this, "Successfully Unpublished the file", "Success", JOptionPane.DEFAULT_OPTION);
                    this.setVisible(false);
                    parent.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error Unpublishing the file", "Failure!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Unpublish.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUnpublishActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonUnpublish;
    private javax.swing.JList jListFiles;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
